# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'rnDandychef' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rnDandychef

  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.11.0'

  # [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
  # pod 'Firebase/AdMob', '~> 5.11.0'
  pod 'Firebase/Auth', '~> 5.11.0'
  pod 'Firebase/Core', '~> 5.11.0'
  pod 'Firebase/Database', '~> 5.11.0'
  pod 'Firebase/Functions', '~> 5.11.0'
  # pod 'Firebase/DynamicLinks', '~> 5.11.0'
  pod 'Firebase/Firestore', '~> 5.11.0'
  # pod 'Firebase/Invites', '~> 5.11.0'
  # pod 'Firebase/Messaging', '~> 5.11.0'
  # pod 'Firebase/RemoteConfig', '~> 5.11.0'
  pod 'Firebase/Storage', '~> 5.11.0'
  # pod 'Firebase/Performance', '~> 5.11.0'
  pod 'Firebase/MLVision'
  pod 'Firebase/MLVisionTextModel'

  pod 'Fabric', '~> 1.7.13'
  pod 'GoogleAppMeasurement', '~> 5.3.0'
  pod 'Crashlytics', '~> 3.10.9'

  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    #'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
    'RCTImage'
  ]

  pod 'react-native-camera', path: '../node_modules/react-native-camera', subspecs: [
    'TextDetector'
  ]

  pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'

  pod 'GoogleSignIn'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end

end
